using System;
using System.Linq;
using System.Windows.Forms;

using KhayelitshaLibrary.WinForms.Models;
using KhayelitshaLibrary.WinForms.Repositories;

namespace KhayelitshaLibrary.WinForms.Forms
{
    public partial class BookForm : Form
    {
        public BookForm()
        {
            InitializeComponent();

            // =============================================================
            // CONNECT EVENTS
            // =============================================================
            //
            // We explicitly connect the buttons and grids here.
            // The -= prevents duplicate event handlers if the Designer
            // has already connected them.
            //

            btnAdd.Click -= btnAdd_Click;
            btnAdd.Click += btnAdd_Click;

            btnUpdate.Click -= btnUpdate_Click;
            btnUpdate.Click += btnUpdate_Click;

            btnDelete.Click -= btnDelete_Click;
            btnDelete.Click += btnDelete_Click;

            btnClear.Click -= btnClear_Click;
            btnClear.Click += btnClear_Click;

            btnAddCopy.Click -= btnAddCopy_Click;
            btnAddCopy.Click += btnAddCopy_Click;

            btnUpdateCopy.Click -= btnUpdateCopy_Click;
            btnUpdateCopy.Click += btnUpdateCopy_Click;

            btnDeleteCopy.Click -= btnDeleteCopy_Click;
            btnDeleteCopy.Click += btnDeleteCopy_Click;

            btnClearCopy.Click -= btnClearCopy_Click;
            btnClearCopy.Click += btnClearCopy_Click;

            dataGridViewBooks.CellClick -= dataGridViewBooks_CellClick;
            dataGridViewBooks.CellClick += dataGridViewBooks_CellClick;

            dataGridViewCopies.CellClick -= dataGridViewCopies_CellClick;
            dataGridViewCopies.CellClick += dataGridViewCopies_CellClick;

            // =============================================================
            // CONFIGURE
            // =============================================================

            ConfigureForm();

            // =============================================================
            // LOAD DATA
            // =============================================================

            LoadBooks();

            LoadBookTitlesIntoComboBox();

            LoadBookCopies();
        }


        // =================================================================
        // CONFIGURE FORM
        // =================================================================

        private void ConfigureForm()
        {
            // Book Title ID is generated by PostgreSQL
            txtBookTitleID.ReadOnly = true;

            // Copy ID is generated by PostgreSQL
            txtCopyID.ReadOnly = true;

            // -------------------------------------------------------------
            // COPY STATUS COMBOBOX
            // -------------------------------------------------------------

            cmbCopyStatus.Items.Clear();

            cmbCopyStatus.Items.Add("Available");
            cmbCopyStatus.Items.Add("On Loan");

            cmbCopyStatus.SelectedIndex = -1;

            // -------------------------------------------------------------
            // CLEAR FIELDS
            // -------------------------------------------------------------

            ClearFields();

            ClearCopyFields();
        }


        // =================================================================
        // LOAD BOOK TITLES
        // =================================================================

        private void LoadBooks()
        {
            try
            {
                var repository = new BookTitleRepository();

                var books = repository.GetAllBookTitles();

                dataGridViewBooks.DataSource = books;

                dataGridViewBooks.AutoSizeColumnsMode =
                    DataGridViewAutoSizeColumnsMode.Fill;

                dataGridViewBooks.SelectionMode =
                    DataGridViewSelectionMode.FullRowSelect;

                dataGridViewBooks.MultiSelect = false;

                dataGridViewBooks.ReadOnly = true;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load books.\n\n{ex.Message}",
                    "Book Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // LOAD BOOK TITLES INTO COPY COMBOBOX
        // =================================================================

        private void LoadBookTitlesIntoComboBox()
        {
            try
            {
                var repository = new BookTitleRepository();

                var books = repository.GetAllBookTitles();

                cmbCopyBookTitle.DataSource = null;

                cmbCopyBookTitle.DisplayMember = "Title";

                cmbCopyBookTitle.ValueMember = "BookTitleID";

                cmbCopyBookTitle.DataSource = books;

                cmbCopyBookTitle.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load book titles into the copy list.\n\n{ex.Message}",
                    "Book Copy Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // LOAD PHYSICAL BOOK COPIES
        // =================================================================

        private void LoadBookCopies()
        {
            try
            {
                var copyRepository = new BookCopyRepository();

                var titleRepository = new BookTitleRepository();

                var copies =
                    copyRepository.GetAllBookCopies();

                var books =
                    titleRepository.GetAllBookTitles();

                // ---------------------------------------------------------
                // Create lookup:
                //
                // BookTitleID -> Book Title
                // ---------------------------------------------------------

                var bookTitles = books.ToDictionary(
                    book => book.BookTitleID,
                    book => book.Title
                );

                // ---------------------------------------------------------
                // Create display list
                // ---------------------------------------------------------

                var copyDisplayList = copies.Select(copy => new
                {
                    CopyID = copy.CopyID,

                    BookTitleID = copy.BookTitleID,

                    Title = bookTitles.ContainsKey(copy.BookTitleID)
                        ? bookTitles[copy.BookTitleID]
                        : "Unknown Book",

                    Status = copy.Status

                }).ToList();

                // ---------------------------------------------------------
                // Display in DataGridView
                // ---------------------------------------------------------

                dataGridViewCopies.DataSource =
                    copyDisplayList;

                dataGridViewCopies.AutoSizeColumnsMode =
                    DataGridViewAutoSizeColumnsMode.Fill;

                dataGridViewCopies.SelectionMode =
                    DataGridViewSelectionMode.FullRowSelect;

                dataGridViewCopies.MultiSelect = false;

                dataGridViewCopies.ReadOnly = true;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load book copies.\n\n{ex.Message}",
                    "Book Copy Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // ADD BOOK TITLE
        // =================================================================

        private void btnAdd_Click(object sender, EventArgs e)
        {
            try
            {
                // ---------------------------------------------------------
                // VALIDATE TITLE
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtTitle.Text))
                {
                    MessageBox.Show(
                        "Please enter a book title.",
                        "Missing Title",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    txtTitle.Focus();

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE AUTHOR
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtAuthor.Text))
                {
                    MessageBox.Show(
                        "Please enter the author.",
                        "Missing Author",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    txtAuthor.Focus();

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE ISBN
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtISBN.Text))
                {
                    MessageBox.Show(
                        "Please enter the ISBN.",
                        "Missing ISBN",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    txtISBN.Focus();

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE CATEGORY
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtCategory.Text))
                {
                    MessageBox.Show(
                        "Please enter the category.",
                        "Missing Category",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    txtCategory.Focus();

                    return;
                }

                // ---------------------------------------------------------
                // CREATE BOOK
                // ---------------------------------------------------------

                var book = new BookTitle
                {
                    Title = txtTitle.Text.Trim(),

                    Author = txtAuthor.Text.Trim(),

                    ISBN = txtISBN.Text.Trim(),

                    Category = txtCategory.Text.Trim()
                };

                // ---------------------------------------------------------
                // INSERT
                // ---------------------------------------------------------

                var repository =
                    new BookTitleRepository();

                repository.AddBookTitle(book);

                // ---------------------------------------------------------
                // REFRESH
                // ---------------------------------------------------------

                LoadBooks();

                LoadBookTitlesIntoComboBox();

                LoadBookCopies();

                ClearFields();

                // ---------------------------------------------------------
                // SUCCESS
                // ---------------------------------------------------------

                MessageBox.Show(
                    "Book title added successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to add book title.\n\n{ex.Message}",
                    "Book Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // UPDATE BOOK TITLE
        // =================================================================

        private void btnUpdate_Click(object sender, EventArgs e)
        {
            try
            {
                // ---------------------------------------------------------
                // VALIDATE ID
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtBookTitleID.Text))
                {
                    MessageBox.Show(
                        "Please select a book to update.",
                        "Update Book",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                if (!int.TryParse(
                    txtBookTitleID.Text.Trim(),
                    out int bookTitleID))
                {
                    MessageBox.Show(
                        "Invalid Book Title ID.",
                        "Update Book",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE FIELDS
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtTitle.Text) ||
                    string.IsNullOrWhiteSpace(txtAuthor.Text) ||
                    string.IsNullOrWhiteSpace(txtISBN.Text) ||
                    string.IsNullOrWhiteSpace(txtCategory.Text))
                {
                    MessageBox.Show(
                        "Please complete all book fields.",
                        "Update Book",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // CREATE BOOK
                // ---------------------------------------------------------

                var book = new BookTitle
                {
                    BookTitleID = bookTitleID,

                    Title = txtTitle.Text.Trim(),

                    Author = txtAuthor.Text.Trim(),

                    ISBN = txtISBN.Text.Trim(),

                    Category = txtCategory.Text.Trim()
                };

                // ---------------------------------------------------------
                // UPDATE
                // ---------------------------------------------------------

                var repository =
                    new BookTitleRepository();

                repository.UpdateBookTitle(book);

                // ---------------------------------------------------------
                // REFRESH
                // ---------------------------------------------------------

                LoadBooks();

                LoadBookTitlesIntoComboBox();

                LoadBookCopies();

                ClearFields();

                // ---------------------------------------------------------
                // SUCCESS
                // ---------------------------------------------------------

                MessageBox.Show(
                    "Book title updated successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to update book title.\n\n{ex.Message}",
                    "Book Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // DELETE BOOK TITLE
        // =================================================================

        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                // ---------------------------------------------------------
                // VALIDATE ID
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtBookTitleID.Text))
                {
                    MessageBox.Show(
                        "Please select a book to delete.",
                        "Delete Book",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                if (!int.TryParse(
                    txtBookTitleID.Text.Trim(),
                    out int bookTitleID))
                {
                    MessageBox.Show(
                        "Invalid Book Title ID.",
                        "Delete Book",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // CONFIRM
                // ---------------------------------------------------------

                DialogResult result = MessageBox.Show(
                    "Are you sure you want to delete this book title?",
                    "Confirm Delete",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question
                );

                if (result != DialogResult.Yes)
                {
                    return;
                }

                // ---------------------------------------------------------
                // DELETE
                // ---------------------------------------------------------

                var repository =
                    new BookTitleRepository();

                repository.DeleteBookTitle(bookTitleID);

                // ---------------------------------------------------------
                // REFRESH
                // ---------------------------------------------------------

                LoadBooks();

                LoadBookTitlesIntoComboBox();

                LoadBookCopies();

                ClearFields();

                // ---------------------------------------------------------
                // SUCCESS
                // ---------------------------------------------------------

                MessageBox.Show(
                    "Book title deleted successfully.",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to delete book title.\n\n{ex.Message}",
                    "Book Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // CLEAR BOOK TITLE FIELDS
        // =================================================================

        private void ClearFields()
        {
            txtBookTitleID.Clear();

            txtTitle.Clear();

            txtAuthor.Clear();

            txtISBN.Clear();

            txtCategory.Clear();

            if (dataGridViewBooks.Rows.Count > 0)
            {
                dataGridViewBooks.ClearSelection();
            }
        }


        // =================================================================
        // BOOK TITLE GRID CLICK
        // =================================================================

        private void dataGridViewBooks_CellClick(
            object sender,
            DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0)
            {
                return;
            }

            try
            {
                var row =
                    dataGridViewBooks.Rows[e.RowIndex];

                txtBookTitleID.Text =
                    row.Cells["BookTitleID"]
                        .Value?
                        .ToString();

                txtTitle.Text =
                    row.Cells["Title"]
                        .Value?
                        .ToString();

                txtAuthor.Text =
                    row.Cells["Author"]
                        .Value?
                        .ToString();

                txtISBN.Text =
                    row.Cells["ISBN"]
                        .Value?
                        .ToString();

                txtCategory.Text =
                    row.Cells["Category"]
                        .Value?
                        .ToString();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load selected book.\n\n{ex.Message}",
                    "Book Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // CLEAR BOOK TITLE BUTTON
        // =================================================================

        private void btnClear_Click(object sender, EventArgs e)
        {
            ClearFields();
        }


        // =================================================================
        // ADD PHYSICAL BOOK COPY
        // =================================================================

        private void btnAddCopy_Click(object sender, EventArgs e)
        {
            try
            {
                // ---------------------------------------------------------
                // VALIDATE BOOK TITLE
                // ---------------------------------------------------------

                if (cmbCopyBookTitle.SelectedIndex == -1 ||
                    cmbCopyBookTitle.SelectedValue == null)
                {
                    MessageBox.Show(
                        "Please select a book title.",
                        "Missing Book",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    cmbCopyBookTitle.Focus();

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE STATUS
                // ---------------------------------------------------------

                if (cmbCopyStatus.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a copy status.",
                        "Missing Status",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    cmbCopyStatus.Focus();

                    return;
                }

                // ---------------------------------------------------------
                // GET VALUES
                // ---------------------------------------------------------

                int bookTitleID =
                    Convert.ToInt32(
                        cmbCopyBookTitle.SelectedValue
                    );

                string status =
                    cmbCopyStatus.SelectedItem?
                        .ToString() ?? string.Empty;

                // ---------------------------------------------------------
                // CREATE BOOK COPY
                // ---------------------------------------------------------

                var copy = new BookCopy
                {
                    BookTitleID = bookTitleID,

                    Status = status
                };

                // ---------------------------------------------------------
                // INSERT
                // ---------------------------------------------------------

                var repository =
                    new BookCopyRepository();

                repository.AddBookCopy(copy);

                // ---------------------------------------------------------
                // REFRESH GRID
                // ---------------------------------------------------------

                LoadBookCopies();

                ClearCopyFields();

                // ---------------------------------------------------------
                // SUCCESS
                // ---------------------------------------------------------

                MessageBox.Show(
                    "Book copy added successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to add book copy.\n\n{ex.Message}",
                    "Book Copy Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // UPDATE PHYSICAL BOOK COPY
        // =================================================================

        private void btnUpdateCopy_Click(object sender, EventArgs e)
        {
            try
            {
                // ---------------------------------------------------------
                // VALIDATE COPY ID
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtCopyID.Text))
                {
                    MessageBox.Show(
                        "Please select a book copy to update.",
                        "Update Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                if (!int.TryParse(
                    txtCopyID.Text.Trim(),
                    out int copyID))
                {
                    MessageBox.Show(
                        "Invalid Copy ID.",
                        "Update Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE BOOK TITLE
                // ---------------------------------------------------------

                if (cmbCopyBookTitle.SelectedIndex == -1 ||
                    cmbCopyBookTitle.SelectedValue == null)
                {
                    MessageBox.Show(
                        "Please select a book title.",
                        "Update Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // VALIDATE STATUS
                // ---------------------------------------------------------

                if (cmbCopyStatus.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a status.",
                        "Update Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // GET VALUES
                // ---------------------------------------------------------

                int bookTitleID =
                    Convert.ToInt32(
                        cmbCopyBookTitle.SelectedValue
                    );

                string status =
                    cmbCopyStatus.SelectedItem?
                        .ToString() ?? string.Empty;

                // ---------------------------------------------------------
                // CREATE BOOK COPY
                // ---------------------------------------------------------

                var copy = new BookCopy
                {
                    CopyID = copyID,

                    BookTitleID = bookTitleID,

                    Status = status
                };

                // ---------------------------------------------------------
                // UPDATE
                // ---------------------------------------------------------

                var repository =
                    new BookCopyRepository();

                repository.UpdateBookCopy(copy);

                // ---------------------------------------------------------
                // REFRESH
                // ---------------------------------------------------------

                LoadBookCopies();

                ClearCopyFields();

                // ---------------------------------------------------------
                // SUCCESS
                // ---------------------------------------------------------

                MessageBox.Show(
                    "Book copy updated successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to update book copy.\n\n{ex.Message}",
                    "Book Copy Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // DELETE PHYSICAL BOOK COPY
        // =================================================================

        private void btnDeleteCopy_Click(object sender, EventArgs e)
        {
            try
            {
                // ---------------------------------------------------------
                // VALIDATE COPY ID
                // ---------------------------------------------------------

                if (string.IsNullOrWhiteSpace(txtCopyID.Text))
                {
                    MessageBox.Show(
                        "Please select a book copy to delete.",
                        "Delete Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                if (!int.TryParse(
                    txtCopyID.Text.Trim(),
                    out int copyID))
                {
                    MessageBox.Show(
                        "Invalid Copy ID.",
                        "Delete Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                // ---------------------------------------------------------
                // CONFIRM DELETE
                // ---------------------------------------------------------

                DialogResult result = MessageBox.Show(
                    "Are you sure you want to delete this physical book copy?",
                    "Confirm Delete",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question
                );

                if (result != DialogResult.Yes)
                {
                    return;
                }

                // ---------------------------------------------------------
                // DELETE
                // ---------------------------------------------------------

                var repository =
                    new BookCopyRepository();

                repository.DeleteBookCopy(copyID);

                // ---------------------------------------------------------
                // REFRESH
                // ---------------------------------------------------------

                LoadBookCopies();

                ClearCopyFields();

                // ---------------------------------------------------------
                // SUCCESS
                // ---------------------------------------------------------

                MessageBox.Show(
                    "Book copy deleted successfully.",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to delete book copy.\n\n{ex.Message}",
                    "Book Copy Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // CLEAR PHYSICAL BOOK COPY FIELDS
        // =================================================================

        private void ClearCopyFields()
        {
            txtCopyID.Clear();

            cmbCopyBookTitle.SelectedIndex = -1;

            cmbCopyStatus.SelectedIndex = -1;

            if (dataGridViewCopies.Rows.Count > 0)
            {
                dataGridViewCopies.ClearSelection();
            }
        }


        // =================================================================
        // BOOK COPY GRID CLICK
        // =================================================================

        private void dataGridViewCopies_CellClick(
            object sender,
            DataGridViewCellEventArgs e)
        {
            if (e.RowIndex < 0)
            {
                return;
            }

            try
            {
                var row =
                    dataGridViewCopies.Rows[e.RowIndex];

                // ---------------------------------------------------------
                // COPY ID
                // ---------------------------------------------------------

                txtCopyID.Text =
                    row.Cells["CopyID"]
                        .Value?
                        .ToString();

                // ---------------------------------------------------------
                // BOOK TITLE ID
                // ---------------------------------------------------------

                object bookTitleValue =
                    row.Cells["BookTitleID"].Value;

                if (bookTitleValue != null)
                {
                    int bookTitleID =
                        Convert.ToInt32(bookTitleValue);

                    cmbCopyBookTitle.SelectedValue =
                        bookTitleID;
                }

                // ---------------------------------------------------------
                // STATUS
                // ---------------------------------------------------------

                string status =
                    row.Cells["Status"]
                        .Value?
                        .ToString() ?? string.Empty;

                cmbCopyStatus.SelectedItem = status;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load selected book copy.\n\n{ex.Message}",
                    "Book Copy Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================
        // CLEAR COPY BUTTON
        // =================================================================

        private void btnClearCopy_Click(object sender, EventArgs e)
        {
            ClearCopyFields();
        }


        // =================================================================
        // FORM LOAD
        // =================================================================

        private void BookForm_Load(object sender, EventArgs e)
        {
        }
    }
}