using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows.Forms;

using KhayelitshaLibrary.WinForms.Models;
using KhayelitshaLibrary.WinForms.Repositories;

namespace KhayelitshaLibrary.WinForms.Forms
{
    public partial class LoanForm : Form
    {
        public LoanForm()
        {
            InitializeComponent();

            // Load all dropdown data
            LoadMembers();
            LoadBookCopies();
            LoadStaff();

            // Load all loans into the grid
            LoadLoans();

            // Configure default form values
            ConfigureForm();
        }


        // =================================================================================================
        // CONFIGURE FORM
        // =================================================================================================

        private void ConfigureForm()
        {
            // Loan ID is generated by PostgreSQL.
            // The user should not manually enter it.
            txtLoanID.ReadOnly = true;

            // No member selected initially
            cmbMember.SelectedIndex = -1;

            // No book copy selected initially
            cmbBookCopy.SelectedIndex = -1;

            // No staff member selected initially
            cmbStaff.SelectedIndex = -1;

            // Default loan date = today
            dtpLoanDate.Value = DateTime.Today;

            // Default due date = 14 days from today
            dtpDueDate.Value = DateTime.Today.AddDays(14);

            // No return date initially
            chkReturned.Checked = false;

            // Disable return date until the loan is marked as returned
            dtpReturnDate.Enabled = false;
        }


        // =================================================================================================
        // LOAD MEMBERS
        // =================================================================================================

        private void LoadMembers()
        {
            try
            {
                var repository = new MemberRepository();

                var members = repository.GetAllMembers();

                var memberDisplayList = new List<object>();

                foreach (var member in members)
                {
                    memberDisplayList.Add(new
                    {
                        MemberID = member.MemberID,

                        DisplayName =
                            $"{member.MemberID} - {member.FirstName} {member.LastName}"
                    });
                }

                cmbMember.DataSource = memberDisplayList;
                cmbMember.DisplayMember = "DisplayName";
                cmbMember.ValueMember = "MemberID";

                cmbMember.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load members.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================================================
        // LOAD AVAILABLE BOOK COPIES
        // =================================================================================================

        private void LoadBookCopies(int? selectedCopyID = null)
        {
            try
            {
                var repository = new BookCopyRepository();

                // Get copies that are available for new loans
                var copies = repository.GetAvailableBookCopies();

                // If we are editing an existing loan,
                // also include its currently assigned copy.
                if (selectedCopyID.HasValue)
                {
                    var selectedCopy = repository.GetBookCopyById(
                        selectedCopyID.Value
                    );

                    if (selectedCopy != null &&
                        !copies.Any(c => c.CopyID == selectedCopy.CopyID))
                    {
                        copies.Add(selectedCopy);
                    }
                }

                var copyDisplayList = new List<object>();

                foreach (var copy in copies)
                {
                    copyDisplayList.Add(new
                    {
                        CopyID = copy.CopyID,

                        DisplayName =
                            $"Copy {copy.CopyID} - Book Title {copy.BookTitleID} - {copy.Status}"
                    });
                }

                cmbBookCopy.DataSource = copyDisplayList;
                cmbBookCopy.DisplayMember = "DisplayName";
                cmbBookCopy.ValueMember = "CopyID";

                cmbBookCopy.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load book copies.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================================================
        // LOAD STAFF
        // =================================================================================================

        private void LoadStaff()
        {
            try
            {
                var repository = new StaffRepository();

                var staffMembers = repository.GetAllStaff();

                var staffDisplayList = new List<object>();

                foreach (var staff in staffMembers)
                {
                    staffDisplayList.Add(new
                    {
                        StaffID = staff.StaffID,

                        DisplayName =
                            $"{staff.StaffID} - {staff.FirstName} {staff.LastName}"
                    });
                }

                cmbStaff.DataSource = staffDisplayList;
                cmbStaff.DisplayMember = "DisplayName";
                cmbStaff.ValueMember = "StaffID";

                cmbStaff.SelectedIndex = -1;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load staff members.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================================================
        // LOAD ALL LOANS
        // =================================================================================================

        private void LoadLoans()
        {
            try
            {
                var repository = new LoanRepository();

                var loans = repository.GetAllLoans();

                dataGridView1.DataSource = loans;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load loans.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }

        // =================================================================================================
        // ADD LOAN
        // =================================================================================================

        private void btnAdd_Click_1(object sender, EventArgs e)
        {
            try
            {
                // -----------------------------------------------------------------------------------------
                // Validate Member
                // -----------------------------------------------------------------------------------------

                if (cmbMember.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a member.",
                        "Missing Member",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // -----------------------------------------------------------------------------------------
                // Validate Book Copy
                // -----------------------------------------------------------------------------------------

                if (cmbBookCopy.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a book copy.",
                        "Missing Book Copy",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // -----------------------------------------------------------------------------------------
                // Validate Staff
                // -----------------------------------------------------------------------------------------

                if (cmbStaff.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a staff member.",
                        "Missing Staff",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // -----------------------------------------------------------------------------------------
                // Validate Due Date
                // -----------------------------------------------------------------------------------------

                if (dtpDueDate.Value.Date < dtpLoanDate.Value.Date)
                {
                    MessageBox.Show(
                        "Due date cannot be before the loan date.",
                        "Invalid Dates",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // -----------------------------------------------------------------------------------------
                // Validate Return Date
                // -----------------------------------------------------------------------------------------

                if (chkReturned.Checked &&
                    dtpReturnDate.Value.Date < dtpLoanDate.Value.Date)
                {
                    MessageBox.Show(
                        "Return date cannot be before the loan date.",
                        "Invalid Dates",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // -----------------------------------------------------------------------------------------
                // Get selected IDs
                // -----------------------------------------------------------------------------------------

                int memberId = Convert.ToInt32(cmbMember.SelectedValue);

                int copyId = Convert.ToInt32(cmbBookCopy.SelectedValue);

                int staffId = Convert.ToInt32(cmbStaff.SelectedValue);


                // -----------------------------------------------------------------------------------------
                // Create Loan object
                // -----------------------------------------------------------------------------------------

                var loan = new Loan
                {
                    MemberID = memberId,

                    CopyID = copyId,

                    StaffID = staffId,

                    LoanDate = DateOnly.FromDateTime(
                        dtpLoanDate.Value),

                    DueDate = DateOnly.FromDateTime(
                        dtpDueDate.Value),

                    ReturnDate = chkReturned.Checked
                        ? DateOnly.FromDateTime(dtpReturnDate.Value)
                        : null
                };


                // -----------------------------------------------------------------------------------------
                // Add loan to database
                // -----------------------------------------------------------------------------------------

                var repository = new LoanRepository();

                repository.AddLoan(loan);


                // -----------------------------------------------------------------------------------------
                // Refresh loan grid
                // -----------------------------------------------------------------------------------------

                LoadLoans();


                // -----------------------------------------------------------------------------------------
                // Refresh available book copies
                // -----------------------------------------------------------------------------------------

                LoadBookCopies();


                // -----------------------------------------------------------------------------------------
                // Reset form
                // -----------------------------------------------------------------------------------------

                ConfigureForm();


                // -----------------------------------------------------------------------------------------
                // Success message
                // -----------------------------------------------------------------------------------------

                MessageBox.Show(
                    "Loan added successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to add loan.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }


        // =================================================================================================
        // RETURNED CHECKBOX
        // =================================================================================================

        private void chkReturned_CheckedChanged_1(object sender, EventArgs e)
        {
            dtpReturnDate.Enabled = chkReturned.Checked;

            if (!chkReturned.Checked)
            {
                dtpReturnDate.Value = DateTime.Today;
            }
        }

        // =================================================================================================
        // CLEAR FIELDS
        // =================================================================================================

        private void ClearFields()
        {
            txtLoanID.Text = "";

            cmbMember.SelectedIndex = -1;
            cmbBookCopy.SelectedIndex = -1;
            cmbStaff.SelectedIndex = -1;

            dtpLoanDate.Value = DateTime.Today;
            dtpDueDate.Value = DateTime.Today.AddDays(14);

            chkReturned.Checked = false;
            dtpReturnDate.Value = DateTime.Today;
            dtpReturnDate.Enabled = false;

            dataGridView1.ClearSelection();

            LoadMembers();
            LoadBookCopies();
            LoadStaff();
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
            try
            {
                // =================================================================
                // VALIDATE LOAN ID
                // =================================================================

                if (string.IsNullOrWhiteSpace(txtLoanID.Text))
                {
                    MessageBox.Show(
                        "Please select a loan to update.",
                        "Loan Error",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                int loanID = int.Parse(txtLoanID.Text);


                // =================================================================
                // VALIDATE MEMBER
                // =================================================================

                if (cmbMember.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a member.",
                        "Loan Error",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // =================================================================
                // VALIDATE BOOK COPY
                // =================================================================

                if (cmbBookCopy.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a book copy.",
                        "Loan Error",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // =================================================================
                // VALIDATE STAFF
                // =================================================================

                if (cmbStaff.SelectedIndex == -1)
                {
                    MessageBox.Show(
                        "Please select a staff member.",
                        "Loan Error",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // =================================================================
                // GET VALUES FROM FORM
                // =================================================================

                int memberID = Convert.ToInt32(cmbMember.SelectedValue);

                int copyID = Convert.ToInt32(cmbBookCopy.SelectedValue);

                int staffID = Convert.ToInt32(cmbStaff.SelectedValue);

                DateOnly loanDate = DateOnly.FromDateTime(
                    dtpLoanDate.Value
                );

                DateOnly dueDate = DateOnly.FromDateTime(
                    dtpDueDate.Value
                );


                // =================================================================
                // VALIDATE DATES
                // =================================================================

                if (dueDate < loanDate)
                {
                    MessageBox.Show(
                        "The due date cannot be before the loan date.",
                        "Loan Error",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // =================================================================
                // GET RETURN DATE
                // =================================================================

                DateOnly? returnDate = null;

                if (chkReturned.Checked)
                {
                    returnDate = DateOnly.FromDateTime(
                        dtpReturnDate.Value
                    );

                    if (returnDate.Value < loanDate)
                    {
                        MessageBox.Show(
                            "The return date cannot be before the loan date.",
                            "Loan Error",
                            MessageBoxButtons.OK,
                            MessageBoxIcon.Warning
                        );

                        return;
                    }
                }


                // =================================================================
                // CREATE LOAN OBJECT
                // =================================================================

                var loan = new Loan
                {
                    LoanID = loanID,
                    MemberID = memberID,
                    CopyID = copyID,
                    StaffID = staffID,
                    LoanDate = loanDate,
                    DueDate = dueDate,
                    ReturnDate = returnDate
                };


                // =================================================================
                // UPDATE DATABASE
                // =================================================================

                var repository = new LoanRepository();

                repository.UpdateLoan(loan);


                // =================================================================
                // SUCCESS
                // =================================================================

                MessageBox.Show(
                    "Loan updated successfully!",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );


                // =================================================================
                // REFRESH EVERYTHING
                // =================================================================

                LoadLoans();

                LoadBookCopies();

                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to update loan.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }

        private void dataGridView1_CellClick(object sender, DataGridViewCellEventArgs e)
        {
            // Ignore clicks on the header
            if (e.RowIndex < 0)
            {
                return;
            }

            try
            {
                // Get the selected loan from the grid
                int loanId = Convert.ToInt32(
                    dataGridView1.Rows[e.RowIndex]
                        .Cells["LoanID"]
                        .Value
                );

                var repository = new LoanRepository();

                var loan = repository.GetLoanById(loanId);

                if (loan == null)
                {
                    MessageBox.Show(
                        "Loan could not be found.",
                        "Loan Error",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Error
                    );

                    return;
                }

                // -------------------------------------------------------------
                // LOAD LOAN ID
                // -------------------------------------------------------------

                txtLoanID.Text = loan.LoanID.ToString();


                // -------------------------------------------------------------
                // LOAD MEMBER
                // -------------------------------------------------------------

                cmbMember.SelectedValue = loan.MemberID;


                // -------------------------------------------------------------
                // LOAD BOOK COPY
                // -------------------------------------------------------------

                LoadBookCopies(loan.CopyID);

                cmbBookCopy.SelectedValue = loan.CopyID;


                // -------------------------------------------------------------
                // LOAD STAFF
                // -------------------------------------------------------------

                cmbStaff.SelectedValue = loan.StaffID;


                // -------------------------------------------------------------
                // LOAD DATES
                // -------------------------------------------------------------

                dtpLoanDate.Value = loan.LoanDate.ToDateTime(
                    TimeOnly.MinValue
                );

                dtpDueDate.Value = loan.DueDate.ToDateTime(
                    TimeOnly.MinValue
                );


                // -------------------------------------------------------------
                // LOAD RETURN INFORMATION
                // -------------------------------------------------------------

                if (loan.ReturnDate.HasValue)
                {
                    chkReturned.Checked = true;

                    dtpReturnDate.Value = loan.ReturnDate.Value.ToDateTime(
                        TimeOnly.MinValue
                    );
                }
                else
                {
                    chkReturned.Checked = false;

                    dtpReturnDate.Value = DateTime.Today;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to load loan.\n\n{ex.Message}",
                    "Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            try
            {
                // =============================================================
                // VALIDATE LOAN ID
                // =============================================================

                if (string.IsNullOrWhiteSpace(txtLoanID.Text))
                {
                    MessageBox.Show(
                        "Please select a loan to delete.",
                        "Delete Loan",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }

                if (!int.TryParse(txtLoanID.Text, out int loanID))
                {
                    MessageBox.Show(
                        "Invalid Loan ID.",
                        "Delete Loan",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    return;
                }


                // =============================================================
                // CONFIRM DELETE
                // =============================================================

                DialogResult result = MessageBox.Show(
                    "Are you sure you want to delete this loan?",
                    "Confirm Delete",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question
                );

                if (result != DialogResult.Yes)
                {
                    return;
                }


                // =============================================================
                // DELETE FROM DATABASE
                // =============================================================

                var repository = new LoanRepository();

                repository.DeleteLoan(loanID);


                // =============================================================
                // SUCCESS
                // =============================================================

                MessageBox.Show(
                    "Loan deleted successfully.",
                    "Success",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );


                // =============================================================
                // REFRESH EVERYTHING
                // =============================================================

                LoadLoans();

                LoadMembers();

                LoadBookCopies();

                LoadStaff();

                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to delete loan.\n\n{ex.Message}",
                    "Delete Loan Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            ClearFields();
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            try
            {
                LoadLoans();
                ClearFields();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to refresh data.\n\n{ex.Message}",
                    "Refresh Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }

        private void btnSearch_Click(object sender, EventArgs e)
        {
            try
            {
                // =============================================================
                // VALIDATE SEARCH ID
                // =============================================================

                if (string.IsNullOrWhiteSpace(txtLoanID.Text))
                {
                    MessageBox.Show(
                        "Please enter a Loan ID.",
                        "Search Loan",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    txtLoanID.Focus();
                    return;
                }

                if (!int.TryParse(txtLoanID.Text.Trim(), out int loanId))
                {
                    MessageBox.Show(
                        "Please enter a valid numeric Loan ID.",
                        "Search Loan",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Warning
                    );

                    txtLoanID.Focus();
                    txtLoanID.SelectAll();
                    return;
                }


                // =============================================================
                // SEARCH DATABASE
                // =============================================================

                var repository = new LoanRepository();

                var loan = repository.GetLoanById(loanId);


                // =============================================================
                // LOAN NOT FOUND
                // =============================================================

                if (loan == null)
                {
                    MessageBox.Show(
                        $"No loan was found with Loan ID {loanId}.",
                        "Loan Not Found",
                        MessageBoxButtons.OK,
                        MessageBoxIcon.Information
                    );

                    return;
                }


                // =============================================================
                // LOAD LOAN ID
                // =============================================================

                txtLoanID.Text = loan.LoanID.ToString();


                // =============================================================
                // LOAD MEMBER
                // =============================================================

                cmbMember.SelectedValue = loan.MemberID;


                // =============================================================
                // LOAD BOOK COPY
                // =============================================================

                // Important:
                // Include the current copy even if it is currently On Loan.
                LoadBookCopies(loan.CopyID);

                cmbBookCopy.SelectedValue = loan.CopyID;


                // =============================================================
                // LOAD STAFF
                // =============================================================

                cmbStaff.SelectedValue = loan.StaffID;


                // =============================================================
                // LOAD DATES
                // =============================================================

                dtpLoanDate.Value = loan.LoanDate.ToDateTime(
                    TimeOnly.MinValue
                );

                dtpDueDate.Value = loan.DueDate.ToDateTime(
                    TimeOnly.MinValue
                );


                // =============================================================
                // LOAD RETURN INFORMATION
                // =============================================================

                if (loan.ReturnDate.HasValue)
                {
                    chkReturned.Checked = true;

                    dtpReturnDate.Enabled = true;

                    dtpReturnDate.Value =
                        loan.ReturnDate.Value.ToDateTime(
                            TimeOnly.MinValue
                        );
                }
                else
                {
                    chkReturned.Checked = false;

                    dtpReturnDate.Enabled = false;

                    dtpReturnDate.Value = DateTime.Today;
                }


                // =============================================================
                // SUCCESS
                // =============================================================

                MessageBox.Show(
                    "Loan found successfully.",
                    "Search",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Failed to search for loan.\n\n{ex.Message}",
                    "Search Error",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error
                );
            }
        }
    }
}